output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value       = local.kubeconfig
}


output kubeconfig_location {
    description = "Where the kubeconfig file is stored"
    value = local.kubeconfig_final_loc
}

output kubeconfig_context {
  description = "The cluster's default context"
  value = "The EKS cluster's default context is ${local.config_cluster_name}"
}

output cluster_name {
  description = "Name of the cluster, whether constructed or explicit."
  value = local.eks_cluster_name
}

output cluster_endpoint {
  description = "EKS cluster endpoint."
  value = var.create_cluster ? aws_eks_cluster.main[0].endpoint : null
}

output cluster_oidc_url {
  value = var.create_cluster ? replace(local.oidc_url, "https://","") : null
  description = "Cluster's OIDC URL"
}

output oidc_provider_arn {
  description = "ARN of OIDC provider."
  value = var.enable_oidc && var.create_cluster ? aws_iam_openid_connect_provider.oidc_provider[0].arn : ""
}

output certificate_authority {
  value = var.create_cluster ? aws_eks_cluster.main[0].certificate_authority : null
  description = "CA data for the cluster."
}

output worker_group_arn {
    description = "Worker gorup ARN"
    value = var.create_cluster && var.create_node_group ?  module.node_group[0].arn : null
}

output worker_group_role_arn {
    description = "Worker gorup IAM role ARN"
    value = var.create_cluster && var.create_node_group ?  module.node_group[0].role_arn : null
}